language: erlang
otp_release:
  - 19.2
install:
  - ./rebar3 update
  - make
before_script:
  - epmd -daemon
script:
  - make test
  - make xref
  - make dialyzer
  - make lint
notifications:
  email: christopher.meiklejohn@gmail.com
  slack: lasp-lang:hiPRNnbUa3zdGrrXZfGRAF7D
  irc: "irc.freenode.org#lasp-lang"
sudo: false
